### ISSUE TITLE
pojo的一个问题

### ISSUE THREAD

**Issue by THYLOVEZQ** [MglKsy/hospital#1]
User表的这两行代码是啥意思    
@TableField(exist = false)
private static final long serialVersionUID = 1L;
@MglKsy

**Comment by MglKsy** [comment]
用mybatis-plus自动生成的 实体类，我也不知道是啥😂应该没啥用

**Comment by MglKsy** [comment]
自动生成这么一个字段，之前跟着做项目的时候 也是看见有这个字段，但是没用过

**Comment by THYLOVEZQ** [comment]
OK，应该是MyBatis Plus操作时需要进行序列化
